hyperparameters:
  batch_size: 10 # NEVER SET IT HIGHER THAN 16, IT WILL CRASH
  num_workers: 8
  d_learning_rate: 1e-4
  g_learning_rate: 1e-4

  d_scheduler_step_size: 100
  d_scheduler_gamma: 1
  g_scheduler_step_size: 100
  g_scheduler_gamma: 1

  max_epochs: 1000
  train_fraction: 0.02 
  val_fraction: 0.1
  alpha_penalty: 10    # 10 used in UnSE paper
  alpha_fidelity: 10    # 10 used in UnSE paper
  n_critic: 10         # 10 used in UnSE paper

  weight_clip: True
  weight_clip_value: 0.01
  
wandb:
  use_wandb: True
  logging_freq: 1
  entity: turtle_team
  name: ${now:%d/%m %H:%M:%S}
  project: bachelor2

data:
  clean_processed_path: 'data/clean_processed/'
  noisy_processed_path: 'data/noisy_processed/'
  split: [0.8, 0.1, 0.1]
