hyperparameters:
  batch_size: 10 # NEVER SET IT HIGHER THAN 16, IT WILL CRASH
  num_workers: 8
  d_learning_rate: 1e-4
  g_learning_rate: 1e-4
  max_epochs: 5
  data_fraction: 1
  alpha_penalty: 10    # 10 used in UnSE paper
  alpha_fidelity: 10    # 10 used in UnSE paper
  n_critic: 10         # 10 used in UnSE paper
  
wandb:
  use_wandb: False
  logging_freq: 1
  entity: turtle_team
  name: ${now:%d/%m %H:%M:%S}
  project: bachelor2

data:
  clean_processed_path: 'data/clean_processed/'
  noisy_processed_path: 'data/noisy_processed/'
  split: [0.8, 0.1, 0.1]
