hyperparameters:
  batch_size: 2 # NEVER SET IT HIGHER THAN 16, IT WILL CRASH
  num_workers: 10
  d_learning_rate: 1e-4     # 1e-4  used in UnSE paper
  g_learning_rate: 1e-4     # 1e-4  used in UnSE paper

  d_scheduler_step_size: 1000
  d_scheduler_gamma: 1
  g_scheduler_step_size: 1000
  g_scheduler_gamma: 1

  max_epochs: 1000
  train_fraction: 0.01
  val_fraction: 0.1
  alpha_penalty: 10    # 10 used in UnSE paper
  alpha_fidelity: 10    # 10 used in UnSE paper
  n_critic: 10         # 10 used in UnSE paper

  weight_clip: False
  weight_clip_value: 0.01
  
wandb:
  use_wandb: True
  logging_freq: 1
  entity: turtle_team
  name: ${now:%d/%m %H:%M:%S}
  project: bachelor2

system:
  num_gpus: 0
  checkpointing: True
  continue_training: False
  ckpt_path: "outputs/2024-02-20/16-55-01/models/epoch=654.ckpt" # Or none
