hyperparameters:
  batch_size: 16
  num_workers: 8
  learning_rate: 1e-4
  max_epochs: 1
  data_fraction: 1
  alpha_penalty: 10    # 10 used in UnSE paper
  alpha_fidelity: 10   # 10 used in UnSE paper
  
wandb:
  entity: bachelor_gan
  name: run_${now:%Y-%m-%d_%H-%M-%S}
  project: test_runs

data:
  clean_processed_path: 'data/clean_raw/'
  noisy_processed_path: 'data/noisy_raw/'
  split: [0.8, 0.1, 0.1]
