hyperparameters:
  batch_size: 16
  num_gpus: 1
  max_epochs: 10000
  d_learning_rate: 1e-4     # 1e-4  used in UnSE paper
  g_learning_rate: 1e-4     # 1e-4  used in UnSE paper
  alpha_penalty: 10    # 10 used in UnSE paper
  alpha_fidelity: 10   # 10 used in UnSE paper
  n_critic: 10         # 10 used in UnSE paper

  dataset: "VCTK"   # "VCTK", "AudioSet", "Speaker", "Finetune", "Unsuper50p" or "dummy" 
  num_speakers: 7         # Used if dataset is "Speaker" or "FineTune"
  train_fraction: 1.
  val_fraction: 1.
  sisnr_loss: False    # False or integer alpha value (automatically set to 10 if dataset is "Finetune")

system:
  checkpointing: True
  continue_training: False
  ckpt_path: "models/Standard_Model.ckpt" # Or none
  num_workers: 20

wandb:
  name: ${now:%d/%m %H:%M:%S}
  log_all_scores: False # Causes slow training. Automatically turns on in val if dataset is "AudioSet"
  use_wandb: True
  entity: turtle_team
  project: bachelor2
  